#!/bin/sh

SH_SHEBANG_REGEX="^#!/bin/sh"
BASH_SHEBANG_REGEX="^#!/bin/bash"

is_bash() {
    head -n 1 "${1:?}" | grep -q -e "${BASH_SHEBANG_REGEX:?}"
}

Top="${1:?}"

S=0
for F in \
    $(for D in \
          "${Top:?}"/bin \
          "${Top:?}"/ci.d \
          "${Top:?}"/lib \
          "${Top:?}"/libexec \
          "${Top:?}"/sbin
      do
          find $D -type f -exec sh -c "head -n 1 "{}" | grep -q -e '${SH_SHEBANG_REGEX:?}' -e '${BASH_SHEBANG_REGEX:?}'" \; -print
      done)
do
    printf "%b" "$F"
    is_bash "$F" && printf "%b" '\t(bash)'
    echo
    is_bash "$F" || { checkbashisms "$F" || S=$?; }
    shellcheck "$F" || S=$?
    bashate -i E003 "$F" || true
done
exit ${S:?}
