#!/bin/sh -ex

## AS A
## developer
## I WANT
## to install my development environment automatically and without
## resorting to administrator permissions
## SO THAT
## the development environment is reproducible and easy to set up.

## I want to get Ansible as early as possible. As running Ansible from
## source or installing it via Pip require administrator permissions
## for setup, I install Ansible via Homebrew. Homebrew needs git
## therefore...
##
## Manually install Git from OSX
## TODO Invoke git on a OSX machine without git and then put here the command for installing it
##
## Manually install Homebrew
HOMEBREW_PREFIX=~/homebrew
git clone https://github.com/Homebrew/homebrew.git $HOMEBREW_PREFIX
HOMEBREW_PATH=${HOMEBREW_PREFIX}/bin
##
## ... and finally...
## Manually install Ansible
PATH=$HOMEBREW_PATH:$PATH brew update
PATH=$HOMEBREW_PATH:$PATH brew install ansible
