#!/bin/sh

type -p docker-daemon-on-machine-start > /dev/null && \
    { M="$(docker-daemon-on-machine-start)" || \
            { echo "Error while starting Docker daemon on Docker Machine. Exiting." >&2
              exit 1
            }
    } && \
        { eval "$(docker-machine env ${M})" || \
                { echo "Error while setting environment for Docker client. Exiting." >&2
                  exit 1
                }
        }
docker run -it --rm -v /Users/$(whoami):/Users/$(whoami) -w "$(pwd)" -e CLASSPATH java:openjdk-8-jdk "$@"
## You can install JavaFX running the following in the container:
## ```
## $ apt-get update && apt-get install -y openjfx && rm -rf /var/lib/apt/lists/*
## ```
