#!/bin/sh
type -p docker-daemon-on-machine-start > /dev/null \
    && { M="$(docker-daemon-on-machine-start)" \
               || { echo "Error while starting Docker daemon on Docker Machine." >&2; \
                    exit 1; }; } \
    && { eval "$(docker-machine env ${M})" \
               || { echo "Error while setting environment for Docker client." >&2; \
                    exit 1; }; }
docker run -it --rm -v /Users/$(whoami):/Users/$(whoami) -w "$(pwd)" -e CLASSPATH lucafavatella/javafx:openjdk-8-jdk-javafx "$@"
