#!/bin/sh -e

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

DOTFILES_PREFIX="${1:?}" ## Mandatory.

DOTFILES_REPO=https://github.com/lucafavatella/dotfiles.git
DOTFILES_DIR=~/dev/dotfiles

HOMEBREW_PREFIX=$(PATH="$(pwd)/lib:$PATH" lib/brew --prefix)
S="ansible-playbook dotfiles.yml -v -i ansible/hosts -e dotfiles_repo=$DOTFILES_REPO -e dotfiles_dir=$DOTFILES_DIR -e dotfiles_prefix=$DOTFILES_PREFIX -c local"
lib/ush -v --path-prefix "${HOMEBREW_PREFIX}/bin:" "$S"
