#!/bin/sh -e

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

BREW_INSTALL="${1:-$(pwd)/brew_install}" ## Overridden for testing.
DOTFILES_PREFIX="${2:-~}" ## Overridden for testing.

echo "Consider running ./.osx" >&2
git --version > /dev/null ## Rely on OSX to prompt user to install Xcode Command Line Tools - not full Xcode.
./run_brew "brew install ansible" "$BREW_INSTALL" ## Ansible required by following steps.
./link_dotfiles "$DOTFILES_PREFIX"
