#!/bin/sh -e

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

BREW_INSTALL="${1:-$(pwd)/brew_install}" ## Overridden for testing.
DOTFILES_PREFIX="${2:-~}" ## Overridden for testing.

PROVISIONING_OSX_BIN_DIR="$(pwd)/lib"

git --version > /dev/null ## Rely on OSX to prompt user to install Xcode Command Line Tools - not full Xcode.

./run_brew "brew install ansible" "$BREW_INSTALL" ## Ansible required by following steps.
echo "Consider running ./run_brew_as_admin" >&2

./.osx
echo "Consider running ./.osx --enable-sudo" >&2

./link_bins "$PROVISIONING_OSX_BIN_DIR"
./link_dotfiles "$DOTFILES_PREFIX"
