#!/bin/sh -e

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

set -e

log() {
    local C=$(basename "$0")
    echo "[$C] $1"
}

log_e() {
    log "$1" >&2
}

BREW_INSTALL="${1:-$(pwd)/brew_install}" ## Overridden for testing.
DOTFILES_PREFIX="${2:-~}" ## Overridden for testing.

PROVISIONING_OSX_BIN_DIR="$(pwd)/lib"

git --version > /dev/null ## Rely on OSX to prompt user to install Xcode Command Line Tools - not full Xcode.

./run_brew "brew install ansible" "$BREW_INSTALL" ## Ansible required by following steps.
log_e "Consider running './run_brew_as_admin'"
log_e "You should manually run 'brew cask install --force' of any Homebrew Casks you deem requiring upgrade" ## Ref https://github.com/caskroom/homebrew-cask/issues/4678

./.osx | grep -v "^Dropping command 'sudo .*'. Pass option '--enable-sudo' in order not to drop command.$"
log_e "Consider running './.osx --enable-sudo'"

./link_bins "$PROVISIONING_OSX_BIN_DIR"
./link_dotfiles "$DOTFILES_PREFIX"
