#!/bin/sh

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

set -e

log() {
    echo "[$(basename $0)] ${1:?}"
}

log_e() {
    log "${1:?}" >&2
}

ROOT_DIR="$(cd $(dirname $0)/.. && pwd)"

log_e "You are supposed to have run '${ROOT_DIR}/bin/provision_osx'"
"${ROOT_DIR}/libexec/make_usr_local" "$ROOT_DIR"
"${ROOT_DIR}/libexec/run_brew_as_admin" "$ROOT_DIR"
"${ROOT_DIR}/libexec/.osx" --enable-sudo
