#!/bin/sh -e

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

set -x

ROOT_DIR="$(cd $(dirname $0)/.. && pwd)"

"${ROOT_DIR}/libexec/make_usr_local" "$ROOT_DIR"
"${ROOT_DIR}/libexec/run_brew_as_admin" "$ROOT_DIR"
"${ROOT_DIR}/libexec/.osx" --enable-sudo
