#!/bin/sh

set -e

log() {
    echo "[$(basename "$0")] ${1:?}"
}

log_e() {
    log "${1:?}" >&2
}

ROOT_DIR="$(cd "$(dirname "$0")"/.. && pwd)"

MACOS_REPO=https://github.com/lucafavatella/mathiasbynens-dotfiles.git
MACOS_VERSION=c9a0dec
MACOS_DIR="${ROOT_DIR:?}"/home/provisioning-osx.d/mathiasbynens-dotfiles
MACOS_ORIGIN=provisioning-osx

log_e "You are supposed to have run '${ROOT_DIR}/bin/provision_osx'"
"${ROOT_DIR}"/bin/ush -c -v "export PATH=\"${ROOT_DIR}/bin:\${PATH}\" && ${ROOT_DIR}/libexec/brew_install_as_admin"
mkdir -p "${MACOS_DIR:?}" \
    && /usr/bin/make -f "${ROOT_DIR:?}"/bin/git-get REPO="${MACOS_REPO:?}" VERSION="${MACOS_VERSION:?}" DIR="${MACOS_DIR:?}" ORIGIN="${MACOS_ORIGIN:?}" \
    && "${MACOS_DIR:?}"/.macos
