#!/bin/sh

set -e

brew cask install lulu ## At least at first install requires restart.
brew cask install wireshark
brew cask install spectacle

brew cask install virtualbox
brew cask install vagrant

#brew cask install intel-haxm
brew cask install java
