#!/bin/sh

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

set -e

brew cask install spectacle

brew cask install flash-npapi

brew cask install virtualbox
brew cask install vagrant

brew cask install java
#brew cask install wireshark
