#!/bin/sh -e

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

brew cask install sizeup ## TODO Move to Spectacle https://www.spectacleapp.com - see also .osx

brew cask install iterm2
brew install tmux
brew install bash-completion
brew install git ## For git-completion.
brew install emacs

brew cask install caskroom/versions/firefoxdeveloperedition

#brew install packer
brew install docker
brew install docker-machine ## Downloads boot2docker.iso
brew install ansible
#brew install ssh-copy-id

#brew cask install android-studio
brew install autoconf
#brew install bats
#brew install checkbashisms
#brew install cmake
#brew install dash
#brew install gdb
{ brew rm ctags || true; } && brew install --HEAD universal-ctags/homebrew-universal-ctags/universal-ctags && brew install global --with-exuberant-ctags --with-pygments ## HACK Using unofficial universal-ctags while using official global that depends on (exuberant-)ctags.
brew install jq
brew install --HEAD homebrew/head-only/kerl
#brew install p7zip
brew install pstree
#brew install pup
#brew install rust
#brew install valgrind
#brew install watch

brew install --with-deps dinkypumpkin/get_iplayer/get_iplayer
