#!/bin/bash

## Using `bash` and not `sh` for non-POSIX `local`.

set -e

log() {
    echo "[$(basename $0)] ${1:?}"
}

log_e() {
    log "${1:?}" >&2
}

brew_cleanup() {
    local C; C=$(brew cleanup -s 2>&1) || { log_e "'brew cleanup -s' failed. Exiting. Info:"$'\n'"$C"; exit 1; }
}

brew_doctor() {
    local D; D=$(brew doctor 2>&1) || { log_e "'brew doctor' detected potential problems. Continuing. Info:"$'\n'"$D"; }
    local CD; CD=$(brew cask doctor 2>&1) || { log_e "'brew cask doctor' detected potential problems. Exiting. Info:"$'\n'"$CD"; exit 1; }
}

BREW_INSTALL1="${1:?}" ## Mandatory.
BREW_INSTALL2="${2:?}" ## Mandatory.

brew update
brew update ## Run `brew update` twice. Ref https://github.com/Homebrew/brew/blob/9ebcef785eed097be709bffef97263b5f536ba34/CONTRIBUTING.md#report-a-bug
brew upgrade

sh -c "$BREW_INSTALL1"
sh -c "$BREW_INSTALL2"

brew_cleanup
brew_doctor
