#!/bin/bash

## Using `bash` and not `sh` for non-POSIX `local`.

set -e

log() {
    echo "[$(basename "$0")] ${1:?}"
}

log_e() {
    log "${1:?}" >&2
}

BREW_INSTALL1="${1:?}" ## Mandatory.
BREW_INSTALL2="${2:?}" ## Mandatory.

sh -c "$BREW_INSTALL1"
sh -c "$BREW_INSTALL2"
