#!/bin/sh -e

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

ROOT_DIR="${1:?}" ## Mandatory.
DOTFILES_PREFIX="${2:?}" ## Mandatory.

DOTFILES_REPO=https://github.com/lucafavatella/dotfiles.git
DOTFILES_DIR=~/dev/dotfiles

HOMEBREW_PREFIX=$(PATH="${ROOT_DIR}/bin:$PATH" "${ROOT_DIR}/bin/brew" --prefix)
S="ansible-playbook ${ROOT_DIR}/lib/dotfiles.yml -i ${ROOT_DIR}/lib/hosts -e dotfiles_repo=$DOTFILES_REPO -e dotfiles_dir=$DOTFILES_DIR -e dotfiles_prefix=$DOTFILES_PREFIX"
"${ROOT_DIR}/bin/ush" -v --path-prefix "${HOMEBREW_PREFIX}/bin:" "$S"
