#!/bin/sh -e

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

ROOT_DIR="${1:?}" ## Mandatory.

DOCKER_BIN_REPO=https://github.com/lucafavatella/docker-bin.git
DOCKER_BIN_DIR=~/dev/docker-bin

HOMEBREW_PREFIX=$(PATH="${ROOT_DIR}/bin:$PATH" "${ROOT_DIR}/bin/brew" --prefix)
S="ansible-playbook ${ROOT_DIR}/lib/home.yml -i ${ROOT_DIR}/lib/hosts -e provisioning_osx_root_dir=${ROOT_DIR} -e docker_bin_repo=$DOCKER_BIN_REPO -e docker_bin_dir=$DOCKER_BIN_DIR"
"${ROOT_DIR}/bin/ush" -v --path-prefix "${HOMEBREW_PREFIX}/bin:" "$S"
