#!/bin/sh -e

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

DOTFILES_PREFIX="${1:?}" ## Mandatory.

DOTFILES_REPO=https://github.com/lucafavatella/dotfiles.git
DOTFILES_DIR=~/dev/dotfiles

HOMEBREW_PREFIX=$(PATH="$(pwd)/bin:$PATH" bin/brew --prefix)
S="ansible-playbook lib/dotfiles.yml -i lib/hosts -e dotfiles_repo=$DOTFILES_REPO -e dotfiles_dir=$DOTFILES_DIR -e dotfiles_prefix=$DOTFILES_PREFIX -c local"
bin/ush -v --path-prefix "${HOMEBREW_PREFIX}/bin:" "$S"
