#!/bin/sh -e

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

ROOT_DIR="${1:?}" ## Mandatory.
DOTFILES_PREFIX="${2:?}" ## Mandatory.

DOTFILES_REPO=https://github.com/lucafavatella/dotfiles.git
DOTFILES_DIR=~/dev/dotfiles

DOCKER_BIN_REPO=https://github.com/lucafavatella/docker-bin.git
DOCKER_BIN_DIR=~/dev/docker-bin

HOMEBREW_PREFIX=$(PATH="${ROOT_DIR}/bin:$PATH" "${ROOT_DIR}/bin/brew" --prefix)
E0="-e provisioning_osx_root_dir=${ROOT_DIR}"
E1="-e dotfiles_repo=${DOTFILES_REPO} -e dotfiles_dir=${DOTFILES_DIR} -e dotfiles_prefix=${DOTFILES_PREFIX}"
E2="-e docker_bin_repo=${DOCKER_BIN_REPO} -e docker_bin_dir=${DOCKER_BIN_DIR}"
S="ansible-playbook ${ROOT_DIR}/lib/home.yml -i ${ROOT_DIR}/lib/hosts $E0 $E1 $E2"
"${ROOT_DIR}/bin/ush" -v --path-prefix "${HOMEBREW_PREFIX}/bin:" "$S"
