#!/bin/sh

set -e

ROOT_DIR="${1:?}" ## Mandatory.

HOMEBREW_PREFIX=$(PATH="${ROOT_DIR}/bin:$PATH" "${ROOT_DIR}/bin/brew" --prefix)
S="ansible-playbook ${ROOT_DIR}/lib/usr_local.yml -i ${ROOT_DIR}/lib/hosts --become --ask-become-pass -vv"
"${ROOT_DIR}"/bin/ush -c -v "export PATH=\"${HOMEBREW_PREFIX}/bin:\${PATH}\" && { $S
}"
