#!/bin/sh -e

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

HOMEBREW_PREFIX=$(PATH="$(pwd)/bin:$PATH" bin/brew --prefix)
S="ansible-playbook lib/usr_local.yml -i lib/hosts -c local --ask-become-pass --become"
bin/ush -v --path-prefix "${HOMEBREW_PREFIX}/bin:" "$S"
