#!/bin/sh

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

set -e

ROOT_DIR="${1:?}" ## Mandatory.
BREW_INSTALL1="${2:?}" ## Mandatory.
BREW_INSTALL2="${3:?}" ## Mandatory.

S="${ROOT_DIR}/libexec/brew_install_wrapper \"${BREW_INSTALL1}\" \"${BREW_INSTALL2}\""
"${ROOT_DIR}"/bin/ush -c -v -p "${ROOT_DIR}/bin:" "$S"
