#!/bin/sh

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

set -e

ROOT_DIR="${1:?}" ## Mandatory.

S="${ROOT_DIR}/libexec/brew_install_as_admin"
"${ROOT_DIR}/bin/ush" -v -p "${ROOT_DIR}/bin:" "$S"
