#!/bin/sh

set -e

ROOT_DIR="${1:?}" ## Mandatory.

DOTFILES_REPO=https://github.com/lucafavatella/dotfiles.git
DOTFILES_DIR="${ROOT_DIR:?}/home/dotfiles"
DOTFILES_ORIGIN="provisioning-osx"
DOTFILES_VERSION="${DOTFILES_ORIGIN:?}/master"
MANAGED_DOTFILES=".bash_profile .gitconfig .emacs"

MANAGED_DIRS="bin"

MANAGED_BINS_FROM_PROVISIONING="brew docker-daemon-on-machine-start emacs-prelude textract"

## Dotfiles e.g. ~/.*

mkdir -p "${DOTFILES_DIR:?}" \
    && env REPO="${DOTFILES_REPO:?}" VERSION="${DOTFILES_VERSION:?}" DIR="${DOTFILES_DIR:?}" ORIGIN="${DOTFILES_ORIGIN:?}" "${ROOT_DIR:?}"/bin/git-get

for F in ${MANAGED_DOTFILES:?}; do
    "${ROOT_DIR:?}"/bin/lns "${DOTFILES_DIR:?}/${F:?}" "${HOME:?}/${F:?}"
done

## Top directories e.g. ~/*

for D in ${MANAGED_DIRS:?}; do
    mkdir -p "${HOME:?}/${D:?}"
done

## Binaries e.g. ~/bin/*

for F in ${MANAGED_BINS_FROM_PROVISIONING:?}; do
    "${ROOT_DIR:?}"/bin/lns "${ROOT_DIR:?}/bin/${F:?}" "${HOME:?}/bin/${F:?}"
done
