#!/bin/sh

## Copyright (C) 2015 Luca Favatella <slackydeb@gmail.com>

set -e

ROOT_DIR="${1:?}" ## Mandatory.
GIT_BUILD_ID="${2:?}" ## Mandatory.

HOME_PREFIX="$HOME"

HOMEBREW_PREFIX=$(PATH="${ROOT_DIR}/bin:$PATH" "${ROOT_DIR}/bin/brew" --prefix)
OPENSSL_PREFIX=$(PATH="${ROOT_DIR}/bin:$PATH" "${ROOT_DIR}/bin/brew" --prefix openssl)
E0="-e home_prefix=${HOME_PREFIX}"
E1="-e homebrew_prefix=${HOMEBREW_PREFIX}"
E2="-e git_build_id=${GIT_BUILD_ID}"
E3="-e openssl_prefix=${OPENSSL_PREFIX}"
S="ansible-playbook ${ROOT_DIR}/lib/home_kerl_installation.yml -i ${ROOT_DIR}/lib/hosts $E0 $E1 $E2 $E3"
"${ROOT_DIR}/bin/ush" -v -p "${HOMEBREW_PREFIX}/bin:" "$S"
