#!/bin/sh -e

## Copyright (C) 2015-2016 Luca Favatella <slackydeb@gmail.com>

ROOT_DIR="${1:?}" ## Mandatory.

HOME_PREFIX="$HOME"

DOTFILES_DIR=~/dev/dotfiles ## Copied from `setup_home`.

HOMEBREW_PREFIX=$(PATH="${ROOT_DIR}/bin:$PATH" "${ROOT_DIR}/bin/brew" --prefix)
E0="-e home_prefix=${HOME_PREFIX}"
E1="-e dotfiles_dir=${DOTFILES_DIR}"
S="ansible-playbook ${ROOT_DIR}/lib/home_otp.yml -i ${ROOT_DIR}/lib/hosts $E0 $E1"
"${ROOT_DIR}/bin/ush" -v --path-prefix "${HOMEBREW_PREFIX}/bin:" "$S"
