#!/bin/sh

set -e

ROOT_DIR="${1:?}" ## Mandatory.
HOME_PREFIX="${2:?}" ## Mandatory.

DOTFILES_REPO=https://github.com/lucafavatella/dotfiles.git
DOTFILES_DIR="${ROOT_DIR}/home/provisioning-osx.d/dotfiles"

HOMEBREW_PREFIX=$(PATH="${ROOT_DIR}/bin/brew" --prefix)
E0="-e provisioning_osx_root_dir=${ROOT_DIR}"
E1="-e home_prefix=${HOME_PREFIX}"
E2="-e dotfiles_repo=${DOTFILES_REPO} -e dotfiles_dir=${DOTFILES_DIR}"
S="ansible-playbook ${ROOT_DIR}/lib/home.yml -i ${ROOT_DIR}/lib/hosts $E0 $E1 $E2 -vv"
"${ROOT_DIR}"/bin/ush -c -v "export PATH=\"${HOMEBREW_PREFIX}/bin:\${PATH}\" && { $S
}"
