#!/bin/sh

set -e

ROOT_DIR="${1:?}" ## Mandatory.
GIT_BUILD_ID="${2:?}" ## Mandatory.

HOMEBREW_PREFIX=$("${ROOT_DIR}/bin/brew" --prefix)
OPENSSL_PREFIX=$("${ROOT_DIR}/bin/brew" --prefix openssl)
WXMAC_PREFIX=$("${ROOT_DIR}/bin/brew" --prefix wxmac)
E0="-e home_prefix=${HOME:?}"
E1="-e git_build_id=${GIT_BUILD_ID}"
E2="-e openssl_prefix=${OPENSSL_PREFIX}"
E3="-e wxmac_prefix=${WXMAC_PREFIX}"
S="ansible-playbook ${ROOT_DIR}/lib/home_kerl_installation.yml -i ${ROOT_DIR}/lib/hosts $E0 $E1 $E2 $E3 -vv"
"${ROOT_DIR}"/bin/ush -c -v "export PATH=\"${HOMEBREW_PREFIX}/bin:\${PATH}\" && { $S
}"
