#!/bin/sh

## Copyright (C) 2015-2016 Luca Favatella <slackydeb@gmail.com>

set -e

ROOT_DIR="${1:?}" ## Mandatory.

HOME_PREFIX="$HOME"

DOTFILES_DIR="${ROOT_DIR}/home/provisioning-osx.d/dotfiles" ## Copied from `setup_home`.

HOMEBREW_PREFIX=$(PATH="${ROOT_DIR}/bin:$PATH" "${ROOT_DIR}/bin/brew" --prefix)
E0="-e home_prefix=${HOME_PREFIX}"
E1="-e dotfiles_dir=${DOTFILES_DIR}"
S="ansible-playbook ${ROOT_DIR}/lib/home_otp.yml -i ${ROOT_DIR}/lib/hosts $E0 $E1 -vv"
"${ROOT_DIR}"/bin/ush -c -v -p "${HOMEBREW_PREFIX}/bin:" "$S"
