#!/bin/sh

set -e

ROOT_DIR="${1:?}" ## Mandatory.
HOME_PREFIX="${2:?}" ## Mandatory.

DOTFILES_REPO=https://github.com/lucafavatella/dotfiles.git
DOTFILES_DIR="${ROOT_DIR}/home/provisioning-osx.d/dotfiles"
DOTFILES_ORIGIN="provisioning-osx"
DOTFILES_VERSION="${DOTFILES_ORIGIN:?}/master"
MANAGED_DOTFILES=".bash_profile .tmux.conf .gitconfig .emacs"

MANAGED_DIRS="dev bin"

EMACS_PRELUDE_REPO=https://github.com/bbatsov/prelude.git
EMACS_PRELUDE_DIR="${HOME_PREFIX}/.emacs-prelude.d/.emacs.d"
EMACS_PRELUDE_ORIGIN="provisioning-osx"
EMACS_PRELUDE_VERSION="${EMACS_PRELUDE_ORIGIN:?}/master"

MANAGED_BINS_FROM_PROVISIONING="brew"

## Dotfiles e.g. ~/.*

mkdir -p "${DOTFILES_DIR:?}" \
    && /usr/bin/make -f "${ROOT_DIR:?}"/bin/git-get REPO="${DOTFILES_REPO:?}" VERSION="${DOTFILES_VERSION:?}" DIR="${DOTFILES_DIR:?}" ORIGIN="${DOTFILES_ORIGIN:?}"

for F in ${MANAGED_DOTFILES:?}; do
    "${ROOT_DIR}"/bin/lns "${DOTFILES_DIR:?}/${F:?}" "${HOME_PREFIX:?}/${F:?}"
done

## Top directories e.g. ~/*

for D in ${MANAGED_DIRS:?}; do
    mkdir -p "${HOME_PREFIX:?}/${D:?}"
done

mkdir -p "${EMACS_PRELUDE_DIR:?}" \
    && /usr/bin/make -f "${ROOT_DIR:?}"/bin/git-get REPO="${EMACS_PRELUDE_REPO:?}" VERSION="${EMACS_PRELUDE_VERSION:?}" DIR="${EMACS_PRELUDE_DIR:?}" ORIGIN="${EMACS_PRELUDE_ORIGIN:?}"

## Binaries e.g. ~/bin/*

for F in ${MANAGED_BINS_FROM_PROVISIONING:?}; do
    "${ROOT_DIR}"/bin/lns "${ROOT_DIR:?}/bin/${F:?}" "${HOME_PREFIX:?}/bin/${F:?}"
done
