on: push
jobs:
  lint:
    runs-on: ubuntu-16.04
    steps:
      - run: sudo apt-get install -y devscripts
      - run: sudo apt-get install -y shellcheck
      - run: sudo apt-get install -y python3-bashate
      - uses: actions/checkout@v2
      - run: |
          "${GITHUB_WORKSPACE:?}"/ci.d/check_all_shell_scripts "${GITHUB_WORKSPACE:?}"
